version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor" ]
