name: MyPy type checker

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install prod deps for correct MyPy work
        run: uv sync --frozen --no-dev

      - name: Install MyPy
        run: uv tool install mypy

      - name: Run MyPy
        run: mypy .