name: MyPy type checker

on:
  push:
    paths:
      - ".github/workflows/type-checker.yaml"
      - "**.py"
  pull_request:
    paths:
      - ".github/workflows/type-checker.yaml"
      - "**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install deps
        run: uv sync --frozen

      - name: Run MyPy
        run: uv run mypy .