name: UI compilation
permissions:
  contents: read
  pull-requests: read

on:
  push:
    paths:
      - ".github/workflows/ui-compile.yaml"
      - "**.py"
  pull_request:
    paths:
      - ".github/workflows/ui-compile.yaml"
      - "**.py"

jobs:
  ui-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
  
      - name: Install deps
        run: uv sync --frozen --no-dev

      - name: Run pyuic
        run: uv run -m PyQt6.uic.pyuic -x src/ui/form.ui > /dev/null
